language: csharp
solution: MathSolver.sln
install:
  - nuget restore MathSolver.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release solution-name.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./MathSolver.Tests/bin/Release/MathSolver.Tests.dll